// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4t60fDpmCoHClLv7jYzjrK6bm6gl_Lac',
    appId: '1:877911790746:web:bbdf59d380efd7bfec3b23',
    messagingSenderId: '877911790746',
    projectId: 'vendorsconnectapp',
    authDomain: 'vendorsconnectapp.firebaseapp.com',
    storageBucket: 'vendorsconnectapp.firebasestorage.app',
    measurementId: 'G-CD331JDTCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JksFXjszKkIJKldMCHap8HB5H9BYBYg',
    appId: '1:877911790746:android:9f6575fb2fb12df9ec3b23',
    messagingSenderId: '877911790746',
    projectId: 'vendorsconnectapp',
    storageBucket: 'vendorsconnectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtDRatnXbvPzRpf_2gNOWDFlSpSzryww',
    appId: '1:877911790746:ios:84c104dfe435e2f5ec3b23',
    messagingSenderId: '877911790746',
    projectId: 'vendorsconnectapp',
    storageBucket: 'vendorsconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.vendorsConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtDRatnXbvPzRpf_2gNOWDFlSpSzryww',
    appId: '1:877911790746:ios:84c104dfe435e2f5ec3b23',
    messagingSenderId: '877911790746',
    projectId: 'vendorsconnectapp',
    storageBucket: 'vendorsconnectapp.firebasestorage.app',
    iosBundleId: 'com.example.vendorsConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4t60fDpmCoHClLv7jYzjrK6bm6gl_Lac',
    appId: '1:877911790746:web:d26e045fa0bbc09dec3b23',
    messagingSenderId: '877911790746',
    projectId: 'vendorsconnectapp',
    authDomain: 'vendorsconnectapp.firebaseapp.com',
    storageBucket: 'vendorsconnectapp.firebasestorage.app',
    measurementId: 'G-HGEP9T5RG5',
  );
}
